# Generated by Django 4.2.22 on 2025-06-09 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_comment_parent_id_comment_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_type', models.CharField(default='emma', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now=True)),
                ('session_status', models.CharField(default='active', max_length=10)),
                ('voca_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('gram_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('fluence_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('completion_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('approp_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('opic_grade', models.CharField(max_length=5)),
                ('shadowing_sentence1', models.CharField(max_length=50)),
                ('shadowing_sentence2', models.CharField(max_length=50)),
                ('shadowing_sentence3', models.CharField(max_length=50)),
                ('shadowing_sentence4', models.CharField(max_length=50)),
                ('shadowing_sentence5', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='message_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_at', models.DateTimeField(auto_now_add=True)),
                ('message_corrected', models.TextField(blank=True, null=True)),
                ('message_why', models.TextField(blank=True, null=True)),
                ('message_error', models.BooleanField(default=False)),
                ('session_feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.session_feedback')),
            ],
        ),
    ]
