# Generated by Django 4.2.22 on 2025-06-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_session_feedback_message_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session_feedback',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session_feedback',
            name='opic_grade',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
